/*
 * demo-data.js — a coherent fictional business used by "Load demo data".
 *
 * GENERATED by scripts/gen-demo-data.mjs — do not hand-edit. Change the
 * generator and re-run it; it is seeded, so the diff shows only what moved.
 *
 * Exists so a demo or evaluation opens onto a CRM that looks lived-in: a
 * pipeline with deals at every stage, projects linked to the companies paying
 * for them, invoices linked to those projects, and overdue and upcoming work.
 *
 * Two placeholders are resolved at load time by js/app.js:
 *   { __rel: n }                  a date n days from today, so nothing goes stale
 *   { __ref: "<key>:<name>" }     a relation, to the seeded record's real id
 *
 * A __ref may only point at a module seeded EARLIER (see the generator).
 *
 * 144 records across 8 modules · 34 relations.
 */
const DEMO_DATA = {
  "businessName": "Lumen Studio",
  "currency": "USD",
  "modules": [
    {
      "key": "projects",
      "name": "Projects",
      "icon": "briefcase",
      "color": "#7839ee",
      "defaultView": "kanban",
      "description": "Work in flight, from first brief to delivery.",
      "fields": [
        {
          "key": "name",
          "label": "Project",
          "type": "text",
          "required": true,
          "showInList": true
        },
        {
          "key": "company",
          "label": "Client",
          "type": "relation",
          "relatedModuleName": "Companies",
          "showInList": true
        },
        {
          "key": "status",
          "label": "Status",
          "type": "select",
          "options": [
            "Discovery",
            "In progress",
            "Review",
            "Delivered",
            "On hold"
          ],
          "showInList": true
        },
        {
          "key": "budget",
          "label": "Budget",
          "type": "currency",
          "showInList": true
        },
        {
          "key": "due",
          "label": "Due",
          "type": "date",
          "showInList": true
        },
        {
          "key": "lead",
          "label": "Lead",
          "type": "text"
        },
        {
          "key": "notes",
          "label": "Notes",
          "type": "textarea"
        }
      ]
    },
    {
      "key": "invoices",
      "name": "Invoices",
      "icon": "receipt",
      "color": "#099250",
      "defaultView": "table",
      "description": "What has been billed, and what is still outstanding.",
      "fields": [
        {
          "key": "number",
          "label": "Number",
          "type": "text",
          "required": true,
          "showInList": true
        },
        {
          "key": "project",
          "label": "Project",
          "type": "relation",
          "relatedModuleName": "Projects",
          "showInList": true
        },
        {
          "key": "amount",
          "label": "Amount",
          "type": "currency",
          "showInList": true
        },
        {
          "key": "status",
          "label": "Status",
          "type": "select",
          "options": [
            "Draft",
            "Sent",
            "Paid",
            "Overdue"
          ],
          "showInList": true
        },
        {
          "key": "issued",
          "label": "Issued",
          "type": "date"
        },
        {
          "key": "due",
          "label": "Due",
          "type": "date",
          "showInList": true
        },
        {
          "key": "notes",
          "label": "Notes",
          "type": "textarea"
        }
      ]
    }
  ],
  "records": {
    "companies": [
      {
        "name": "Bright Bakery",
        "industry": "Food & Beverage",
        "website": "https://brightbakery.example",
        "phone": "+1 555 0923",
        "city": "Portland",
        "notes": ""
      },
      {
        "name": "Okafor Supplies",
        "industry": "Manufacturing",
        "website": "https://okaforsupplies.example",
        "phone": "+1 555 0274",
        "city": "Newark",
        "notes": ""
      },
      {
        "name": "Vesta Interiors",
        "industry": "Services",
        "website": "https://vestainteriors.example",
        "phone": "+1 555 0199",
        "city": "Austin",
        "notes": ""
      },
      {
        "name": "Northgate Dental",
        "industry": "Services",
        "website": "https://northgatedental.example",
        "phone": "+1 555 0634",
        "city": "Columbus",
        "notes": ""
      },
      {
        "name": "Rivera Landscaping",
        "industry": "Services",
        "website": "https://riveralandscaping.example",
        "phone": "+1 555 0377",
        "city": "Tucson",
        "notes": ""
      },
      {
        "name": "Perch Coffee",
        "industry": "Food & Beverage",
        "website": "https://perchcoffee.example",
        "phone": "+1 555 0323",
        "city": "Seattle",
        "notes": ""
      },
      {
        "name": "Aldridge Legal",
        "industry": "Services",
        "website": "https://aldridgelegal.example",
        "phone": "+1 555 0896",
        "city": "Boston",
        "notes": ""
      },
      {
        "name": "Kestrel Fitness",
        "industry": "Retail",
        "website": "https://kestrelfitness.example",
        "phone": "+1 555 0571",
        "city": "Denver",
        "notes": ""
      },
      {
        "name": "Marlow Bookshop",
        "industry": "Retail",
        "website": "https://marlowbookshop.example",
        "phone": "+1 555 0952",
        "city": "Providence",
        "notes": ""
      },
      {
        "name": "Tidewater Plumbing",
        "industry": "Services",
        "website": "https://tidewaterplumbing.example",
        "phone": "+1 555 0185",
        "city": "Norfolk",
        "notes": ""
      },
      {
        "name": "Sunbelt Roofing",
        "industry": "Manufacturing",
        "website": "https://sunbeltroofing.example",
        "phone": "+1 555 0613",
        "city": "Phoenix",
        "notes": ""
      },
      {
        "name": "Clearwater Optics",
        "industry": "Technology",
        "website": "https://clearwateroptics.example",
        "phone": "+1 555 0855",
        "city": "San Jose",
        "notes": ""
      }
    ],
    "contacts": [
      {
        "name": "Amira Hassan",
        "email": "amira@brightbakery.example",
        "phone": "+1 555 0501",
        "company": "Bright Bakery",
        "tags": "supplier",
        "notes": "Renewal conversation due this quarter."
      },
      {
        "name": "Tom Okafor",
        "email": "tom@okaforsupplies.example",
        "phone": "+1 555 0560",
        "company": "Okafor Supplies",
        "tags": "supplier",
        "notes": "Prefers email to phone."
      },
      {
        "name": "Sofia Ramirez",
        "email": "sofia@vestainteriors.example",
        "phone": "+1 555 0170",
        "company": "Vesta Interiors",
        "tags": "customer",
        "notes": "Introduced us to two other studios."
      },
      {
        "name": "Marcus Bell",
        "email": "marcus@northgatedental.example",
        "phone": "+1 555 0366",
        "company": "Northgate Dental",
        "tags": "supplier",
        "notes": ""
      },
      {
        "name": "Yuki Tanaka",
        "email": "yuki@riveralandscaping.example",
        "phone": "+1 555 0534",
        "company": "Rivera Landscaping",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Priya Nair",
        "email": "priya@perchcoffee.example",
        "phone": "+1 555 0172",
        "company": "Perch Coffee",
        "tags": "prospect",
        "notes": ""
      },
      {
        "name": "Daniel Adeyemi",
        "email": "daniel@aldridgelegal.example",
        "phone": "+1 555 0181",
        "company": "Aldridge Legal",
        "tags": "prospect",
        "notes": ""
      },
      {
        "name": "Elena Petrova",
        "email": "elena@kestrelfitness.example",
        "phone": "+1 555 0645",
        "company": "Kestrel Fitness",
        "tags": "prospect",
        "notes": "Best reached after 4pm."
      },
      {
        "name": "Josh Lindqvist",
        "email": "josh@marlowbookshop.example",
        "phone": "+1 555 0215",
        "company": "Marlow Bookshop",
        "tags": "supplier",
        "notes": "Introduced us to two other studios."
      },
      {
        "name": "Fatima Zahra",
        "email": "fatima@tidewaterplumbing.example",
        "phone": "+1 555 0784",
        "company": "Tidewater Plumbing",
        "tags": "supplier",
        "notes": ""
      },
      {
        "name": "Owen Brennan",
        "email": "owen@sunbeltroofing.example",
        "phone": "+1 555 0166",
        "company": "Sunbelt Roofing",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Mei Lin",
        "email": "mei@clearwateroptics.example",
        "phone": "+1 555 0616",
        "company": "Clearwater Optics",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Carlos Duarte",
        "email": "carlos@brightbakery.example",
        "phone": "+1 555 0316",
        "company": "Bright Bakery",
        "tags": "partner",
        "notes": ""
      },
      {
        "name": "Hannah Weiss",
        "email": "hannah@okaforsupplies.example",
        "phone": "+1 555 0165",
        "company": "Okafor Supplies",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Ibrahim Diallo",
        "email": "ibrahim@vestainteriors.example",
        "phone": "+1 555 0877",
        "company": "Vesta Interiors",
        "tags": "partner",
        "notes": "Introduced us to two other studios."
      },
      {
        "name": "Grace Mwangi",
        "email": "grace@northgatedental.example",
        "phone": "+1 555 0197",
        "company": "Northgate Dental",
        "tags": "customer",
        "notes": "Renewal conversation due this quarter."
      },
      {
        "name": "Victor Ilunga",
        "email": "victor@riveralandscaping.example",
        "phone": "+1 555 0512",
        "company": "Rivera Landscaping",
        "tags": "customer",
        "notes": "Signs off on anything over $5k."
      },
      {
        "name": "Noor Al-Amin",
        "email": "noor@perchcoffee.example",
        "phone": "+1 555 0733",
        "company": "Perch Coffee",
        "tags": "supplier",
        "notes": "Introduced us to two other studios."
      },
      {
        "name": "Peter Novak",
        "email": "peter@aldridgelegal.example",
        "phone": "+1 555 0653",
        "company": "Aldridge Legal",
        "tags": "prospect",
        "notes": ""
      },
      {
        "name": "Rosa Delgado",
        "email": "rosa@kestrelfitness.example",
        "phone": "+1 555 0492",
        "company": "Kestrel Fitness",
        "tags": "supplier",
        "notes": ""
      },
      {
        "name": "Simon Achterberg",
        "email": "simon@marlowbookshop.example",
        "phone": "+1 555 0570",
        "company": "Marlow Bookshop",
        "tags": "partner",
        "notes": ""
      },
      {
        "name": "Leila Farouk",
        "email": "leila@tidewaterplumbing.example",
        "phone": "+1 555 0289",
        "company": "Tidewater Plumbing",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Andre Sokolov",
        "email": "andre@sunbeltroofing.example",
        "phone": "+1 555 0877",
        "company": "Sunbelt Roofing",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Bianca Costa",
        "email": "bianca@clearwateroptics.example",
        "phone": "+1 555 0658",
        "company": "Clearwater Optics",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Nathan Cole",
        "email": "nathan@brightbakery.example",
        "phone": "+1 555 0372",
        "company": "Bright Bakery",
        "tags": "customer",
        "notes": ""
      },
      {
        "name": "Ruth Abebe",
        "email": "ruth@okaforsupplies.example",
        "phone": "+1 555 0854",
        "company": "Okafor Supplies",
        "tags": "customer",
        "notes": ""
      }
    ],
    "deals": [
      {
        "title": "Bright Bakery — campaign artwork",
        "value": "45000",
        "stage": "Lead",
        "company": "Bright Bakery",
        "contact": "Amira Hassan",
        "close": {
          "__rel": 2
        },
        "notes": ""
      },
      {
        "title": "Okafor Supplies — website rebuild",
        "value": "11000",
        "stage": "Won",
        "company": "Okafor Supplies",
        "contact": "Tom Okafor",
        "close": {
          "__rel": 11
        },
        "notes": ""
      },
      {
        "title": "Vesta Interiors — trade stand",
        "value": "14500",
        "stage": "Proposal",
        "company": "Vesta Interiors",
        "contact": "Sofia Ramirez",
        "close": {
          "__rel": 6
        },
        "notes": ""
      },
      {
        "title": "Northgate Dental — annual report",
        "value": "46500",
        "stage": "Negotiation",
        "company": "Northgate Dental",
        "contact": "Marcus Bell",
        "close": {
          "__rel": 68
        },
        "notes": ""
      },
      {
        "title": "Rivera Landscaping — brand guidelines",
        "value": "41000",
        "stage": "Negotiation",
        "company": "Rivera Landscaping",
        "contact": "Yuki Tanaka",
        "close": {
          "__rel": 19
        },
        "notes": ""
      },
      {
        "title": "Perch Coffee — brand refresh",
        "value": "31500",
        "stage": "Won",
        "company": "Perch Coffee",
        "contact": "Priya Nair",
        "close": {
          "__rel": -31
        },
        "notes": ""
      },
      {
        "title": "Aldridge Legal — annual report",
        "value": "35500",
        "stage": "Proposal",
        "company": "Aldridge Legal",
        "contact": "Daniel Adeyemi",
        "close": {
          "__rel": 12
        },
        "notes": ""
      },
      {
        "title": "Kestrel Fitness — website rebuild",
        "value": "2000",
        "stage": "Negotiation",
        "company": "Kestrel Fitness",
        "contact": "Elena Petrova",
        "close": {
          "__rel": 28
        },
        "notes": ""
      },
      {
        "title": "Marlow Bookshop — annual report",
        "value": "25500",
        "stage": "Lost",
        "company": "Marlow Bookshop",
        "contact": "Josh Lindqvist",
        "close": {
          "__rel": -33
        },
        "notes": ""
      },
      {
        "title": "Tidewater Plumbing — product photography",
        "value": "25500",
        "stage": "Qualified",
        "company": "Tidewater Plumbing",
        "contact": "Fatima Zahra",
        "close": {
          "__rel": 52
        },
        "notes": ""
      },
      {
        "title": "Sunbelt Roofing — wayfinding system",
        "value": "15500",
        "stage": "Qualified",
        "company": "Sunbelt Roofing",
        "contact": "Owen Brennan",
        "close": {
          "__rel": 22
        },
        "notes": ""
      },
      {
        "title": "Clearwater Optics — campaign artwork",
        "value": "26500",
        "stage": "Qualified",
        "company": "Clearwater Optics",
        "contact": "Mei Lin",
        "close": {
          "__rel": -16
        },
        "notes": ""
      },
      {
        "title": "Bright Bakery — trade stand",
        "value": "3500",
        "stage": "Lead",
        "company": "Bright Bakery",
        "contact": "Carlos Duarte",
        "close": {
          "__rel": -34
        },
        "notes": ""
      },
      {
        "title": "Okafor Supplies — brand refresh",
        "value": "39500",
        "stage": "Proposal",
        "company": "Okafor Supplies",
        "contact": "Hannah Weiss",
        "close": {
          "__rel": 15
        },
        "notes": ""
      },
      {
        "title": "Vesta Interiors — app icon set",
        "value": "2500",
        "stage": "Proposal",
        "company": "Vesta Interiors",
        "contact": "Ibrahim Diallo",
        "close": {
          "__rel": 67
        },
        "notes": ""
      },
      {
        "title": "Northgate Dental — brand guidelines",
        "value": "17000",
        "stage": "Lead",
        "company": "Northgate Dental",
        "contact": "Grace Mwangi",
        "close": {
          "__rel": 62
        },
        "notes": ""
      },
      {
        "title": "Rivera Landscaping — brand refresh",
        "value": "12000",
        "stage": "Qualified",
        "company": "Rivera Landscaping",
        "contact": "Victor Ilunga",
        "close": {
          "__rel": 10
        },
        "notes": ""
      },
      {
        "title": "Perch Coffee — product photography",
        "value": "15000",
        "stage": "Lead",
        "company": "Perch Coffee",
        "contact": "Noor Al-Amin",
        "close": {
          "__rel": -40
        },
        "notes": ""
      },
      {
        "title": "Aldridge Legal — packaging design",
        "value": "13000",
        "stage": "Proposal",
        "company": "Aldridge Legal",
        "contact": "Peter Novak",
        "close": {
          "__rel": -4
        },
        "notes": ""
      },
      {
        "title": "Kestrel Fitness — trade stand",
        "value": "4500",
        "stage": "Won",
        "company": "Kestrel Fitness",
        "contact": "Rosa Delgado",
        "close": {
          "__rel": -18
        },
        "notes": ""
      },
      {
        "title": "Marlow Bookshop — annual report",
        "value": "41000",
        "stage": "Lost",
        "company": "Marlow Bookshop",
        "contact": "Simon Achterberg",
        "close": {
          "__rel": 21
        },
        "notes": ""
      },
      {
        "title": "Tidewater Plumbing — trade stand",
        "value": "46500",
        "stage": "Qualified",
        "company": "Tidewater Plumbing",
        "contact": "Leila Farouk",
        "close": {
          "__rel": 5
        },
        "notes": ""
      }
    ],
    "tasks": [
      {
        "title": "Chase signed proposal — Bright Bakery",
        "due": {
          "__rel": -11
        },
        "priority": "High",
        "status": "Done",
        "assignee": "Daniel",
        "notes": ""
      },
      {
        "title": "Update the portfolio page — Okafor Supplies",
        "due": {
          "__rel": 29
        },
        "priority": "Low",
        "status": "To do",
        "assignee": "Priya",
        "notes": ""
      },
      {
        "title": "Write handover notes — Vesta Interiors",
        "due": {
          "__rel": 13
        },
        "priority": "High",
        "status": "In progress",
        "assignee": "Maya",
        "notes": ""
      },
      {
        "title": "Order print proofs — Northgate Dental",
        "due": {
          "__rel": 21
        },
        "priority": "Medium",
        "status": "Done",
        "assignee": "Sam",
        "notes": ""
      },
      {
        "title": "Review supplier quote — Rivera Landscaping",
        "due": {
          "__rel": -1
        },
        "priority": "Urgent",
        "status": "In progress",
        "assignee": "Sam",
        "notes": ""
      },
      {
        "title": "Schedule photography — Perch Coffee",
        "due": {
          "__rel": 30
        },
        "priority": "Urgent",
        "status": "In progress",
        "assignee": "Priya",
        "notes": ""
      },
      {
        "title": "Draft scope for phase 2 — Aldridge Legal",
        "due": {
          "__rel": 15
        },
        "priority": "Low",
        "status": "In progress",
        "assignee": "Priya",
        "notes": ""
      },
      {
        "title": "Send revised quote — Kestrel Fitness",
        "due": {
          "__rel": 22
        },
        "priority": "Low",
        "status": "To do",
        "assignee": "Priya",
        "notes": ""
      },
      {
        "title": "Review supplier quote — Marlow Bookshop",
        "due": {
          "__rel": 8
        },
        "priority": "Medium",
        "status": "To do",
        "assignee": "Maya",
        "notes": ""
      },
      {
        "title": "Order print proofs — Tidewater Plumbing",
        "due": {
          "__rel": 12
        },
        "priority": "Medium",
        "status": "Done",
        "assignee": "Sam",
        "notes": ""
      },
      {
        "title": "Prepare moodboard — Sunbelt Roofing",
        "due": {
          "__rel": 18
        },
        "priority": "High",
        "status": "Done",
        "assignee": "Priya",
        "notes": ""
      },
      {
        "title": "Export final assets — Clearwater Optics",
        "due": {
          "__rel": 3
        },
        "priority": "Medium",
        "status": "To do",
        "assignee": "Priya",
        "notes": ""
      },
      {
        "title": "Write handover notes — Bright Bakery",
        "due": {
          "__rel": 10
        },
        "priority": "Medium",
        "status": "To do",
        "assignee": "Maya",
        "notes": ""
      },
      {
        "title": "Second round of edits — Okafor Supplies",
        "due": {
          "__rel": 30
        },
        "priority": "High",
        "status": "To do",
        "assignee": "Daniel",
        "notes": ""
      },
      {
        "title": "Invoice for milestone 2 — Vesta Interiors",
        "due": {
          "__rel": 9
        },
        "priority": "Low",
        "status": "Done",
        "assignee": "Daniel",
        "notes": ""
      },
      {
        "title": "Schedule photography — Northgate Dental",
        "due": {
          "__rel": 7
        },
        "priority": "Urgent",
        "status": "To do",
        "assignee": "Maya",
        "notes": ""
      },
      {
        "title": "Schedule photography — Rivera Landscaping",
        "due": {
          "__rel": 26
        },
        "priority": "High",
        "status": "In progress",
        "assignee": "Maya",
        "notes": ""
      },
      {
        "title": "Write handover notes — Perch Coffee",
        "due": {
          "__rel": 1
        },
        "priority": "Medium",
        "status": "To do",
        "assignee": "Priya",
        "notes": ""
      },
      {
        "title": "Review supplier quote — Aldridge Legal",
        "due": {
          "__rel": -3
        },
        "priority": "Medium",
        "status": "In progress",
        "assignee": "Maya",
        "notes": ""
      },
      {
        "title": "Book kickoff call — Kestrel Fitness",
        "due": {
          "__rel": 4
        },
        "priority": "Low",
        "status": "To do",
        "assignee": "Daniel",
        "notes": ""
      },
      {
        "title": "Chase signed proposal — Marlow Bookshop",
        "due": {
          "__rel": 28
        },
        "priority": "High",
        "status": "In progress",
        "assignee": "Sam",
        "notes": ""
      },
      {
        "title": "Check print colour proof — Tidewater Plumbing",
        "due": {
          "__rel": 19
        },
        "priority": "Medium",
        "status": "Done",
        "assignee": "Sam",
        "notes": ""
      },
      {
        "title": "Draft scope for phase 2 — Sunbelt Roofing",
        "due": {
          "__rel": 29
        },
        "priority": "Medium",
        "status": "In progress",
        "assignee": "Daniel",
        "notes": ""
      },
      {
        "title": "Chase signed proposal — Clearwater Optics",
        "due": {
          "__rel": 2
        },
        "priority": "High",
        "status": "To do",
        "assignee": "Sam",
        "notes": ""
      }
    ],
    "leads": [
      {
        "name": "Amira Hassan",
        "company": "Bright Bakery",
        "email": "amira@brightbakery.example",
        "source": "Social",
        "status": "Contacted",
        "notes": ""
      },
      {
        "name": "Marcus Bell",
        "company": "Perch Coffee",
        "email": "marcus@perchcoffee.example",
        "source": "Website",
        "status": "Contacted",
        "notes": ""
      },
      {
        "name": "Daniel Adeyemi",
        "company": "Sunbelt Roofing",
        "email": "daniel@sunbeltroofing.example",
        "source": "Website",
        "status": "New",
        "notes": ""
      },
      {
        "name": "Fatima Zahra",
        "company": "Northgate Dental",
        "email": "fatima@northgatedental.example",
        "source": "Cold outreach",
        "status": "New",
        "notes": ""
      },
      {
        "name": "Carlos Duarte",
        "company": "Marlow Bookshop",
        "email": "carlos@marlowbookshop.example",
        "source": "Referral",
        "status": "Contacted",
        "notes": ""
      },
      {
        "name": "Grace Mwangi",
        "company": "Okafor Supplies",
        "email": "grace@okaforsupplies.example",
        "source": "Website",
        "status": "Contacted",
        "notes": ""
      },
      {
        "name": "Peter Novak",
        "company": "Aldridge Legal",
        "email": "peter@aldridgelegal.example",
        "source": "Website",
        "status": "Qualified",
        "notes": ""
      },
      {
        "name": "Leila Farouk",
        "company": "Clearwater Optics",
        "email": "leila@clearwateroptics.example",
        "source": "Social",
        "status": "Contacted",
        "notes": ""
      },
      {
        "name": "Nathan Cole",
        "company": "Rivera Landscaping",
        "email": "nathan@riveralandscaping.example",
        "source": "Event",
        "status": "Contacted",
        "notes": ""
      },
      {
        "name": "Tom Okafor",
        "company": "Tidewater Plumbing",
        "email": "tom@tidewaterplumbing.example",
        "source": "Social",
        "status": "New",
        "notes": ""
      },
      {
        "name": "Yuki Tanaka",
        "company": "Vesta Interiors",
        "email": "yuki@vestainteriors.example",
        "source": "Referral",
        "status": "Qualified",
        "notes": ""
      },
      {
        "name": "Elena Petrova",
        "company": "Kestrel Fitness",
        "email": "elena@kestrelfitness.example",
        "source": "Event",
        "status": "New",
        "notes": ""
      },
      {
        "name": "Owen Brennan",
        "company": "Bright Bakery",
        "email": "owen@brightbakery.example",
        "source": "Referral",
        "status": "New",
        "notes": ""
      },
      {
        "name": "Hannah Weiss",
        "company": "Perch Coffee",
        "email": "hannah@perchcoffee.example",
        "source": "Website",
        "status": "Qualified",
        "notes": ""
      },
      {
        "name": "Victor Ilunga",
        "company": "Sunbelt Roofing",
        "email": "victor@sunbeltroofing.example",
        "source": "Website",
        "status": "Contacted",
        "notes": ""
      },
      {
        "name": "Rosa Delgado",
        "company": "Northgate Dental",
        "email": "rosa@northgatedental.example",
        "source": "Cold outreach",
        "status": "Unqualified",
        "notes": ""
      }
    ],
    "notes": [
      {
        "title": "Studio is at capacity until the middle of next m",
        "date": {
          "__rel": -19
        },
        "content": "Studio is at capacity until the middle of next month — quote accordingly."
      },
      {
        "title": "Print supplier put prices up 8%",
        "date": {
          "__rel": -10
        },
        "content": "Print supplier put prices up 8%. Update the standard quote template."
      },
      {
        "title": "Three referrals came from Bright Bakery this qua",
        "date": {
          "__rel": -4
        },
        "content": "Three referrals came from Bright Bakery this quarter. Send a thank-you."
      },
      {
        "title": "Retainer clients now cover fixed costs",
        "date": {
          "__rel": -32
        },
        "content": "Retainer clients now cover fixed costs. Anything project-based is margin."
      },
      {
        "title": "Stop quoting fixed-price on anything with more t",
        "date": {
          "__rel": -23
        },
        "content": "Stop quoting fixed-price on anything with more than two rounds of revision."
      },
      {
        "title": "New camera paid for itself on the Perch Coffee s",
        "date": {
          "__rel": -6
        },
        "content": "New camera paid for itself on the Perch Coffee shoot."
      },
      {
        "title": "Two invoices past 30 days",
        "date": {
          "__rel": -39
        },
        "content": "Two invoices past 30 days. Call before sending another reminder."
      },
      {
        "title": "Move the portfolio off the old host before renew",
        "date": {
          "__rel": -33
        },
        "content": "Move the portfolio off the old host before renewal."
      },
      {
        "title": "Kestrel wants a retainer from the new year",
        "date": {
          "__rel": -7
        },
        "content": "Kestrel wants a retainer from the new year — draft terms."
      },
      {
        "title": "Hire question deferred to Q3",
        "date": {
          "__rel": -15
        },
        "content": "Hire question deferred to Q3. Revisit once the pipeline clears."
      }
    ],
    "projects": [
      {
        "name": "Brand refresh — Bright Bakery",
        "company": {
          "__ref": "companies:Bright Bakery"
        },
        "status": "In progress",
        "budget": "20500",
        "due": {
          "__rel": 87
        },
        "lead": "Daniel",
        "notes": ""
      },
      {
        "name": "Website rebuild — Okafor Supplies",
        "company": {
          "__ref": "companies:Okafor Supplies"
        },
        "status": "In progress",
        "budget": "35500",
        "due": {
          "__rel": 88
        },
        "lead": "Daniel",
        "notes": ""
      },
      {
        "name": "Packaging system — Vesta Interiors",
        "company": {
          "__ref": "companies:Vesta Interiors"
        },
        "status": "Review",
        "budget": "6500",
        "due": {
          "__rel": 51
        },
        "lead": "Priya",
        "notes": ""
      },
      {
        "name": "Signage package — Northgate Dental",
        "company": {
          "__ref": "companies:Northgate Dental"
        },
        "status": "Delivered",
        "budget": "24000",
        "due": {
          "__rel": -1
        },
        "lead": "Daniel",
        "notes": ""
      },
      {
        "name": "Menu redesign — Rivera Landscaping",
        "company": {
          "__ref": "companies:Rivera Landscaping"
        },
        "status": "Discovery",
        "budget": "12000",
        "due": {
          "__rel": 68
        },
        "lead": "Priya",
        "notes": ""
      },
      {
        "name": "Campaign artwork — Perch Coffee",
        "company": {
          "__ref": "companies:Perch Coffee"
        },
        "status": "Delivered",
        "budget": "9500",
        "due": {
          "__rel": 63
        },
        "lead": "Maya",
        "notes": ""
      },
      {
        "name": "Brand guidelines — Aldridge Legal",
        "company": {
          "__ref": "companies:Aldridge Legal"
        },
        "status": "In progress",
        "budget": "31000",
        "due": {
          "__rel": 74
        },
        "lead": "Daniel",
        "notes": ""
      },
      {
        "name": "Annual report — Kestrel Fitness",
        "company": {
          "__ref": "companies:Kestrel Fitness"
        },
        "status": "Delivered",
        "budget": "13500",
        "due": {
          "__rel": 53
        },
        "lead": "Maya",
        "notes": ""
      },
      {
        "name": "Wayfinding — Marlow Bookshop",
        "company": {
          "__ref": "companies:Marlow Bookshop"
        },
        "status": "Review",
        "budget": "16000",
        "due": {
          "__rel": 68
        },
        "lead": "Daniel",
        "notes": ""
      },
      {
        "name": "Product photography — Tidewater Plumbing",
        "company": {
          "__ref": "companies:Tidewater Plumbing"
        },
        "status": "In progress",
        "budget": "4000",
        "due": {
          "__rel": 64
        },
        "lead": "Priya",
        "notes": ""
      },
      {
        "name": "Trade stand — Sunbelt Roofing",
        "company": {
          "__ref": "companies:Sunbelt Roofing"
        },
        "status": "On hold",
        "budget": "27500",
        "due": {
          "__rel": 24
        },
        "lead": "Maya",
        "notes": ""
      },
      {
        "name": "Icon set — Clearwater Optics",
        "company": {
          "__ref": "companies:Clearwater Optics"
        },
        "status": "On hold",
        "budget": "37500",
        "due": {
          "__rel": 88
        },
        "lead": "Maya",
        "notes": ""
      },
      {
        "name": "Email templates — Bright Bakery",
        "company": {
          "__ref": "companies:Bright Bakery"
        },
        "status": "Discovery",
        "budget": "40500",
        "due": {
          "__rel": 12
        },
        "lead": "Maya",
        "notes": ""
      },
      {
        "name": "Print collateral — Okafor Supplies",
        "company": {
          "__ref": "companies:Okafor Supplies"
        },
        "status": "Discovery",
        "budget": "4500",
        "due": {
          "__rel": 17
        },
        "lead": "Priya",
        "notes": ""
      },
      {
        "name": "Social kit — Vesta Interiors",
        "company": {
          "__ref": "companies:Vesta Interiors"
        },
        "status": "In progress",
        "budget": "15500",
        "due": {
          "__rel": 35
        },
        "lead": "Daniel",
        "notes": ""
      },
      {
        "name": "Style guide — Northgate Dental",
        "company": {
          "__ref": "companies:Northgate Dental"
        },
        "status": "Review",
        "budget": "36000",
        "due": {
          "__rel": 41
        },
        "lead": "Daniel",
        "notes": ""
      }
    ],
    "invoices": [
      {
        "number": "LS-2026101",
        "project": {
          "__ref": "projects:Brand refresh — Bright Bakery"
        },
        "amount": "5800",
        "status": "Sent",
        "issued": {
          "__rel": -52
        },
        "due": {
          "__rel": -22
        },
        "notes": ""
      },
      {
        "number": "LS-2026102",
        "project": {
          "__ref": "projects:Website rebuild — Okafor Supplies"
        },
        "amount": "12000",
        "status": "Overdue",
        "issued": {
          "__rel": -57
        },
        "due": {
          "__rel": -27
        },
        "notes": "Second reminder sent."
      },
      {
        "number": "LS-2026103",
        "project": {
          "__ref": "projects:Packaging system — Vesta Interiors"
        },
        "amount": "12300",
        "status": "Draft",
        "issued": {
          "__rel": -51
        },
        "due": {
          "__rel": -21
        },
        "notes": ""
      },
      {
        "number": "LS-2026104",
        "project": {
          "__ref": "projects:Signage package — Northgate Dental"
        },
        "amount": "1400",
        "status": "Paid",
        "issued": {
          "__rel": -6
        },
        "due": {
          "__rel": 24
        },
        "notes": ""
      },
      {
        "number": "LS-2026105",
        "project": {
          "__ref": "projects:Menu redesign — Rivera Landscaping"
        },
        "amount": "1500",
        "status": "Sent",
        "issued": {
          "__rel": -64
        },
        "due": {
          "__rel": -34
        },
        "notes": ""
      },
      {
        "number": "LS-2026106",
        "project": {
          "__ref": "projects:Campaign artwork — Perch Coffee"
        },
        "amount": "16700",
        "status": "Draft",
        "issued": {
          "__rel": -5
        },
        "due": {
          "__rel": 25
        },
        "notes": ""
      },
      {
        "number": "LS-2026107",
        "project": {
          "__ref": "projects:Brand guidelines — Aldridge Legal"
        },
        "amount": "3000",
        "status": "Paid",
        "issued": {
          "__rel": -9
        },
        "due": {
          "__rel": 21
        },
        "notes": ""
      },
      {
        "number": "LS-2026108",
        "project": {
          "__ref": "projects:Annual report — Kestrel Fitness"
        },
        "amount": "17200",
        "status": "Paid",
        "issued": {
          "__rel": -39
        },
        "due": {
          "__rel": -9
        },
        "notes": ""
      },
      {
        "number": "LS-2026109",
        "project": {
          "__ref": "projects:Wayfinding — Marlow Bookshop"
        },
        "amount": "16200",
        "status": "Paid",
        "issued": {
          "__rel": -63
        },
        "due": {
          "__rel": -33
        },
        "notes": ""
      },
      {
        "number": "LS-2026110",
        "project": {
          "__ref": "projects:Product photography — Tidewater Plumbing"
        },
        "amount": "12100",
        "status": "Sent",
        "issued": {
          "__rel": -54
        },
        "due": {
          "__rel": -24
        },
        "notes": ""
      },
      {
        "number": "LS-2026111",
        "project": {
          "__ref": "projects:Trade stand — Sunbelt Roofing"
        },
        "amount": "3600",
        "status": "Sent",
        "issued": {
          "__rel": -49
        },
        "due": {
          "__rel": -19
        },
        "notes": ""
      },
      {
        "number": "LS-2026112",
        "project": {
          "__ref": "projects:Icon set — Clearwater Optics"
        },
        "amount": "8600",
        "status": "Overdue",
        "issued": {
          "__rel": -40
        },
        "due": {
          "__rel": -10
        },
        "notes": "Second reminder sent."
      },
      {
        "number": "LS-2026113",
        "project": {
          "__ref": "projects:Email templates — Bright Bakery"
        },
        "amount": "4500",
        "status": "Paid",
        "issued": {
          "__rel": -39
        },
        "due": {
          "__rel": -9
        },
        "notes": ""
      },
      {
        "number": "LS-2026114",
        "project": {
          "__ref": "projects:Print collateral — Okafor Supplies"
        },
        "amount": "14600",
        "status": "Paid",
        "issued": {
          "__rel": -29
        },
        "due": {
          "__rel": 1
        },
        "notes": ""
      },
      {
        "number": "LS-2026115",
        "project": {
          "__ref": "projects:Social kit — Vesta Interiors"
        },
        "amount": "10100",
        "status": "Draft",
        "issued": {
          "__rel": -59
        },
        "due": {
          "__rel": -29
        },
        "notes": ""
      },
      {
        "number": "LS-2026116",
        "project": {
          "__ref": "projects:Style guide — Northgate Dental"
        },
        "amount": "13400",
        "status": "Paid",
        "issued": {
          "__rel": -15
        },
        "due": {
          "__rel": 15
        },
        "notes": ""
      },
      {
        "number": "LS-2026117",
        "project": {
          "__ref": "projects:Brand refresh — Bright Bakery"
        },
        "amount": "8900",
        "status": "Overdue",
        "issued": {
          "__rel": -48
        },
        "due": {
          "__rel": -18
        },
        "notes": "Second reminder sent."
      },
      {
        "number": "LS-2026118",
        "project": {
          "__ref": "projects:Website rebuild — Okafor Supplies"
        },
        "amount": "6300",
        "status": "Sent",
        "issued": {
          "__rel": -70
        },
        "due": {
          "__rel": -40
        },
        "notes": ""
      }
    ]
  }
};

// Replace { __rel: n } placeholders with a date n days from today (YYYY-MM-DD).
// { __ref: … } objects pass through untouched — js/app.js resolves those once
// the records they point at have real ids.
function resolveDemoDates(value) {
  if (Array.isArray(value)) return value.map(resolveDemoDates);
  if (value && typeof value === 'object') {
    if (typeof value.__rel === 'number') {
      const d = new Date();
      d.setDate(d.getDate() + value.__rel);
      return d.toISOString().slice(0, 10);
    }
    if (typeof value.__ref === 'string') return value;
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveDemoDates(v)]));
  }
  return value;
}
